"""first commit

Revision ID: 095640b66ad2
Revises: a2db03bd6484
Create Date: 2022-02-12 21:05:05.877427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095640b66ad2'
down_revision = 'a2db03bd6484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_invoice', sa.Column('product_id', sa.String(), nullable=True))
    op.drop_column('detail_invoice', 'food_id')
    op.drop_column('detail_invoice', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_invoice', sa.Column('total', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('detail_invoice', sa.Column('food_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('detail_invoice', 'product_id')
    # ### end Alembic commands ###
