"""first commit

Revision ID: 2bfee6d62256
Revises: 69eb6fb3e784
Create Date: 2021-12-11 15:23:55.161473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfee6d62256'
down_revision = '69eb6fb3e784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
