"""first commit

Revision ID: 2c99f8ff86b9
Revises: 38a1f829eaa2
Create Date: 2021-12-11 12:21:45.319112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c99f8ff86b9'
down_revision = '38a1f829eaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
