"""first commit

Revision ID: 69eb6fb3e784
Revises: d626d9379e71
Create Date: 2021-12-11 15:23:11.066612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69eb6fb3e784'
down_revision = 'd626d9379e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_client_id'), 'invoice', ['client_id'], unique=True)
    op.create_index(op.f('ix_invoice_id'), 'invoice', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_client_id'), table_name='invoice')
    op.drop_table('invoice')
    # ### end Alembic commands ###
