"""first commit

Revision ID: d626d9379e71
Revises: e3f14178d6da
Create Date: 2021-12-11 15:22:31.514554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd626d9379e71'
down_revision = 'e3f14178d6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
