"""Added daily_production Table

Revision ID: e3f14178d6da
Revises: 2c99f8ff86b9
Create Date: 2021-12-11 13:05:34.205968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f14178d6da'
down_revision = '2c99f8ff86b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_production',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chicken', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_production_chicken'), 'daily_production', ['chicken'], unique=False)
    op.create_index(op.f('ix_daily_production_id'), 'daily_production', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_production_id'), table_name='daily_production')
    op.drop_index(op.f('ix_daily_production_chicken'), table_name='daily_production')
    op.drop_table('daily_production')
    # ### end Alembic commands ###
